// Export utilities for PDF, DOCX, and TXT formats

export async function exportAsPDF(title: string, content: string): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = margin

  // Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(15, 23, 42)
  const titleLines = doc.splitTextToSize(title, maxWidth)
  doc.text(titleLines, margin, y)
  y += titleLines.length * 8 + 6

  // Divider
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.3)
  doc.line(margin, y, pageWidth - margin, y)
  y += 6

  // Meta
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text(`Generated by ForgeMuse AI  ·  ${new Date().toLocaleDateString()}`, margin, y)
  y += 10

  // Content
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(30, 41, 59)

  const lines = doc.splitTextToSize(content, maxWidth)
  for (const line of lines) {
    if (y > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage()
      y = margin
    }
    doc.text(line, margin, y)
    y += 5.5
  }

  // Footer
  const pageCount = doc.internal.pages.length - 1
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`ForgeMuse AI  ·  Page ${i} of ${pageCount}`, margin, doc.internal.pageSize.getHeight() - 10)
  }

  doc.save(`${sanitizeFilename(title)}.pdf`)
}

export async function exportAsDOCX(title: string, content: string): Promise<void> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx')
  const { saveAs } = await import('file-saver')

  const lines = content.split('\n')
  const paragraphs = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by ForgeMuse AI · ${new Date().toLocaleDateString()}`,
          color: '94A3B8',
          size: 18,
        }),
      ],
    }),
    new Paragraph({ text: '' }),
    ...lines.map((line) =>
      new Paragraph({
        children: [
          new TextRun({
            text: line || ' ',
            size: 22,
            color: '1E293B',
          }),
        ],
        spacing: { before: 100, after: 100 },
      })
    ),
    new Paragraph({ text: '' }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'Made with ForgeMuse AI',
          color: '94A3B8',
          size: 18,
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
    }),
  ]

  const doc = new Document({
    sections: [{ properties: {}, children: paragraphs }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${sanitizeFilename(title)}.docx`)
}

export function exportAsTXT(title: string, content: string): void {
  const text = `${title}\n${'='.repeat(title.length)}\nGenerated by ForgeMuse AI · ${new Date().toLocaleDateString()}\n\n${content}\n\n---\nMade with ForgeMuse AI`
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${sanitizeFilename(title)}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-z0-9\-_\s]/gi, '').replace(/\s+/g, '-').substring(0, 80) || 'forgemuse-export'
}
